// <auto-generated />
using System;
using JugueteriaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JugueteriaAPI.Migrations
{
    [DbContext(typeof(JugueteriaContext))]
    partial class JugueteriaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("JugueteriaAPI.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "Juguetes que fomentan el aprendizaje y desarrollo",
                            FechaCreacion = new DateTime(2025, 7, 30, 21, 45, 36, 0, DateTimeKind.Unspecified),
                            ImagenUrl = "/images/educativos.jpg",
                            Nombre = "Juguetes Educativos"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Descripcion = "Bloques, legos y sets de construcción",
                            FechaCreacion = new DateTime(2025, 7, 30, 21, 45, 36, 0, DateTimeKind.Unspecified),
                            ImagenUrl = "/images/construccion.jpg",
                            Nombre = "Juguetes de Construcción"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Descripcion = "Muñecas, peluches y accesorios",
                            FechaCreacion = new DateTime(2025, 7, 30, 21, 45, 36, 0, DateTimeKind.Unspecified),
                            ImagenUrl = "/images/munecas.jpg",
                            Nombre = "Muñecas y Accesorios"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Descripcion = "Juguetes con tecnología y electrónica",
                            FechaCreacion = new DateTime(2025, 7, 30, 21, 45, 36, 0, DateTimeKind.Unspecified),
                            ImagenUrl = "/images/electronicos.jpg",
                            Nombre = "Juguetes Electrónicos"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Descripcion = "Juegos de mesa para toda la familia",
                            FechaCreacion = new DateTime(2025, 7, 30, 21, 45, 36, 0, DateTimeKind.Unspecified),
                            ImagenUrl = "/images/mesa.jpg",
                            Nombre = "Juegos de Mesa"
                        });
                });

            modelBuilder.Entity("JugueteriaAPI.Models.DetallePedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("DetallesPedido");
                });

            modelBuilder.Entity("JugueteriaAPI.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CiudadEnvio")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CodigoPostalEnvio")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("DireccionEnvio")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaEnvio")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaPedido")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Impuestos")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("NumeroPedido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NumeroPedido")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("JugueteriaAPI.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("EdadRecomendada")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("EnOferta")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Marca")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("PrecioOferta")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            CategoriaId = 4,
                            Descripcion = "Auto de carreras de alta velocidad",
                            EdadRecomendada = "4-8 años",
                            EnOferta = false,
                            FechaCreacion = new DateTime(2025, 7, 30, 21, 45, 36, 0, DateTimeKind.Unspecified),
                            ImagenUrl = "https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=400&q=80",
                            Marca = "Hot Wheels",
                            Nombre = "Auto de Carrera",
                            Precio = 1500m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            CategoriaId = 3,
                            Descripcion = "Muñeca elegante con accesorios",
                            EdadRecomendada = "3-8 años",
                            EnOferta = false,
                            FechaCreacion = new DateTime(2025, 7, 30, 21, 45, 36, 0, DateTimeKind.Unspecified),
                            ImagenUrl = "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=400&q=80",
                            Marca = "Barbie",
                            Nombre = "Muñeca",
                            Precio = 1200m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            CategoriaId = 2,
                            Descripcion = "Set de bloques para construir",
                            EdadRecomendada = "6-12 años",
                            EnOferta = false,
                            FechaCreacion = new DateTime(2025, 7, 30, 21, 45, 36, 0, DateTimeKind.Unspecified),
                            ImagenUrl = "https://images.unsplash.com/photo-1464983953574-0892a716854b?auto=format&fit=crop&w=400&q=80",
                            Marca = "Lego",
                            Nombre = "Bloques de Construcción",
                            Precio = 1800m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            CategoriaId = 3,
                            Descripcion = "Peluche suave y abrazable",
                            EdadRecomendada = "0-5 años",
                            EnOferta = false,
                            FechaCreacion = new DateTime(2025, 7, 30, 21, 45, 36, 0, DateTimeKind.Unspecified),
                            ImagenUrl = "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80",
                            Marca = "Fisher-Price",
                            Nombre = "Peluche",
                            Precio = 950m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            CategoriaId = 4,
                            Descripcion = "Auto de carreras de alta velocidad",
                            EdadRecomendada = "4-8 años",
                            EnOferta = true,
                            FechaCreacion = new DateTime(2025, 7, 30, 21, 45, 36, 0, DateTimeKind.Unspecified),
                            ImagenUrl = "https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=400&q=80",
                            Marca = "Hot Wheels",
                            Nombre = "Auto de Carrera",
                            Precio = 1500m,
                            PrecioOferta = 1200m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            CategoriaId = 3,
                            Descripcion = "Muñeca elegante con accesorios",
                            EdadRecomendada = "3-8 años",
                            EnOferta = true,
                            FechaCreacion = new DateTime(2025, 7, 30, 21, 45, 36, 0, DateTimeKind.Unspecified),
                            ImagenUrl = "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=400&q=80",
                            Marca = "Barbie",
                            Nombre = "Muñeca",
                            Precio = 1200m,
                            PrecioOferta = 950m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            CategoriaId = 2,
                            Descripcion = "Set de bloques para construir",
                            EdadRecomendada = "6-12 años",
                            EnOferta = true,
                            FechaCreacion = new DateTime(2025, 7, 30, 21, 45, 36, 0, DateTimeKind.Unspecified),
                            ImagenUrl = "https://images.unsplash.com/photo-1464983953574-0892a716854b?auto=format&fit=crop&w=400&q=80",
                            Marca = "Lego",
                            Nombre = "Bloques de Construcción",
                            Precio = 1800m,
                            PrecioOferta = 1450m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            CategoriaId = 3,
                            Descripcion = "Peluche suave y abrazable",
                            EdadRecomendada = "0-5 años",
                            EnOferta = true,
                            FechaCreacion = new DateTime(2025, 7, 30, 21, 45, 36, 0, DateTimeKind.Unspecified),
                            ImagenUrl = "https://images.unsplash.com/photo-1517935706615-2717063c2225?auto=format&fit=crop&w=400&q=80",
                            Marca = "Fisher-Price",
                            Nombre = "Peluche",
                            Precio = 950m,
                            PrecioOferta = 700m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            CategoriaId = 1,
                            Descripcion = "Puzzle de paisaje para toda la familia",
                            EdadRecomendada = "8+ años",
                            EnOferta = true,
                            FechaCreacion = new DateTime(2025, 7, 30, 21, 45, 36, 0, DateTimeKind.Unspecified),
                            ImagenUrl = "https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=400&q=80",
                            Marca = "Ravensburger",
                            Nombre = "Puzzle 1000 Piezas",
                            Precio = 2500m,
                            PrecioOferta = 1800m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 10,
                            Activo = true,
                            CategoriaId = 4,
                            Descripcion = "Robot educativo para aprender programación",
                            EdadRecomendada = "8-14 años",
                            EnOferta = true,
                            FechaCreacion = new DateTime(2025, 7, 30, 21, 45, 36, 0, DateTimeKind.Unspecified),
                            ImagenUrl = "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=400&q=80",
                            Marca = "TechToys",
                            Nombre = "Robot Programable",
                            Precio = 3200m,
                            PrecioOferta = 2400m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 11,
                            Activo = true,
                            CategoriaId = 1,
                            Descripcion = "Set completo de pinturas y pinceles",
                            EdadRecomendada = "6-12 años",
                            EnOferta = true,
                            FechaCreacion = new DateTime(2025, 7, 30, 21, 45, 36, 0, DateTimeKind.Unspecified),
                            ImagenUrl = "https://images.unsplash.com/photo-1464983953574-0892a716854b?auto=format&fit=crop&w=400&q=80",
                            Marca = "Crayola",
                            Nombre = "Set de Pinturas",
                            Precio = 800m,
                            PrecioOferta = 550m,
                            Stock = 35
                        },
                        new
                        {
                            Id = 12,
                            Activo = true,
                            CategoriaId = 5,
                            Descripcion = "Juego de mesa para toda la familia",
                            EdadRecomendada = "6+ años",
                            EnOferta = true,
                            FechaCreacion = new DateTime(2025, 7, 30, 21, 45, 36, 0, DateTimeKind.Unspecified),
                            ImagenUrl = "https://images.unsplash.com/photo-1517935706615-2717063c2225?auto=format&fit=crop&w=400&q=80",
                            Marca = "Hasbro",
                            Nombre = "Juego de Mesa",
                            Precio = 1800m,
                            PrecioOferta = 1300m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 13,
                            Activo = true,
                            CategoriaId = 2,
                            Descripcion = "Tobogán colorido para el jardín",
                            EdadRecomendada = "2-8 años",
                            EnOferta = false,
                            FechaCreacion = new DateTime(2025, 7, 30, 21, 45, 36, 0, DateTimeKind.Unspecified),
                            ImagenUrl = "https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=400&q=80",
                            Marca = "Little Tikes",
                            Nombre = "Tobogán Arcoíris",
                            Precio = 3500m,
                            Stock = 8
                        },
                        new
                        {
                            Id = 14,
                            Activo = true,
                            CategoriaId = 2,
                            Descripcion = "Columpio para dos niños",
                            EdadRecomendada = "3-10 años",
                            EnOferta = false,
                            FechaCreacion = new DateTime(2025, 7, 30, 21, 45, 36, 0, DateTimeKind.Unspecified),
                            ImagenUrl = "https://images.unsplash.com/photo-1517935706615-2717063c2225?auto=format&fit=crop&w=400&q=80",
                            Marca = "Step2",
                            Nombre = "Columpio doble",
                            Precio = 4200m,
                            Stock = 5
                        },
                        new
                        {
                            Id = 15,
                            Activo = true,
                            CategoriaId = 4,
                            Descripcion = "Pelota oficial de fútbol",
                            EdadRecomendada = "6+ años",
                            EnOferta = false,
                            FechaCreacion = new DateTime(2025, 7, 30, 21, 45, 36, 0, DateTimeKind.Unspecified),
                            ImagenUrl = "https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&w=400&q=80",
                            Marca = "Penalty",
                            Nombre = "Pelota de fútbol",
                            Precio = 1200m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 16,
                            Activo = true,
                            CategoriaId = 1,
                            Descripcion = "Set completo de acuarelas",
                            EdadRecomendada = "6-12 años",
                            EnOferta = false,
                            FechaCreacion = new DateTime(2025, 7, 30, 21, 45, 36, 0, DateTimeKind.Unspecified),
                            ImagenUrl = "https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=400&q=80",
                            Marca = "Crayola",
                            Nombre = "Set de acuarelas",
                            Precio = 800m,
                            Stock = 25
                        });
                });

            modelBuilder.Entity("JugueteriaAPI.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Ciudad")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CodigoPostal")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Apellido = "Pérez",
                            Ciudad = "Madrid",
                            CodigoPostal = "28001",
                            Direccion = "Calle Principal 123",
                            Email = "juan.perez@email.com",
                            FechaRegistro = new DateTime(2025, 7, 30, 21, 45, 36, 0, DateTimeKind.Unspecified),
                            Nombre = "Juan",
                            Telefono = "123456789"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Apellido = "García",
                            Ciudad = "Barcelona",
                            CodigoPostal = "08001",
                            Direccion = "Avenida Central 456",
                            Email = "maria.garcia@email.com",
                            FechaRegistro = new DateTime(2025, 7, 30, 21, 45, 36, 0, DateTimeKind.Unspecified),
                            Nombre = "María",
                            Telefono = "987654321"
                        });
                });

            modelBuilder.Entity("JugueteriaAPI.Models.DetallePedido", b =>
                {
                    b.HasOne("JugueteriaAPI.Models.Pedido", "Pedido")
                        .WithMany("DetallesPedido")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JugueteriaAPI.Models.Producto", "Producto")
                        .WithMany("DetallesPedido")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("JugueteriaAPI.Models.Pedido", b =>
                {
                    b.HasOne("JugueteriaAPI.Models.Usuario", "Usuario")
                        .WithMany("Pedidos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("JugueteriaAPI.Models.Producto", b =>
                {
                    b.HasOne("JugueteriaAPI.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("JugueteriaAPI.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("JugueteriaAPI.Models.Pedido", b =>
                {
                    b.Navigation("DetallesPedido");
                });

            modelBuilder.Entity("JugueteriaAPI.Models.Producto", b =>
                {
                    b.Navigation("DetallesPedido");
                });

            modelBuilder.Entity("JugueteriaAPI.Models.Usuario", b =>
                {
                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
